CREATE TABLE Roles (
    RoleID INT PRIMARY KEY IDENTITY(1,1),
    RoleName NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE Users (
    UserID INT PRIMARY KEY IDENTITY(1,1),
    RoleID INT FOREIGN KEY REFERENCES Roles(RoleID),
    FullName NVARCHAR(150) NOT NULL,
    Email NVARCHAR(100) UNIQUE
);

CREATE TABLE LegalEntities (
    EntityID INT PRIMARY KEY IDENTITY(1,1),
    EntityName NVARCHAR(150) NOT NULL
);

CREATE TABLE Departments (
    DeptID INT PRIMARY KEY IDENTITY(1,1),
    EntityID INT FOREIGN KEY REFERENCES LegalEntities(EntityID),
    DeptName NVARCHAR(100) NOT NULL
);

CREATE TABLE Vacancies (
    VacancyID INT PRIMARY KEY IDENTITY(1,1),
    DeptID INT FOREIGN KEY REFERENCES Departments(DeptID),
    Title NVARCHAR(100) NOT NULL
);

CREATE TABLE AppStatuses (
    StatusID INT PRIMARY KEY IDENTITY(1,1),
    StatusName NVARCHAR(50) NOT NULL 
);

CREATE TABLE Applications (
    AppID INT PRIMARY KEY IDENTITY(1,1),
    CandidateID INT FOREIGN KEY REFERENCES Users(UserID),
    VacancyID INT FOREIGN KEY REFERENCES Vacancies(VacancyID),
    HR_ID INT FOREIGN KEY REFERENCES Users(UserID),
    StatusID INT FOREIGN KEY REFERENCES AppStatuses(StatusID),
    ApplyDate DATETIME NOT NULL,
    ResolutionDate DATETIME 
);

DROP TABLE IF EXISTS Applications;
DROP TABLE IF EXISTS Vacancies;
DROP TABLE IF EXISTS Departments;
DROP TABLE IF EXISTS LegalEntities;
DROP TABLE IF EXISTS AppStatuses;
DROP TABLE IF EXISTS Orders;
DROP TABLE IF EXISTS Vehicles;
DROP TABLE IF EXISTS OrderStatus;
DROP TABLE IF EXISTS Users;
DROP TABLE IF EXISTS Roles;